name: Rust builder

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: PiWarsBot build for Barum Tech Jam
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup toolcchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build PiWarsBot in release mode, if its a release
        uses: actions-rs/cargo@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          command: build
          args: --all --release

      - name: Build PiWarsBot in debug mode
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all

      - name: 'Install (Cargo) binutils, if its release.'
        if: startsWith(github.ref, 'refs/tags/')
        run:
          cargo install cargo-binutils && rustup component add
          llvm-tools-preview

      - name: Strip the PiWarsBot executable, if its a release
        if: startsWith(github.ref, 'refs/tags/')
        run: cargo-strip --release -- --strip-all

      - name: Create release for PiWarsBot, if its a release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./target/release/piwarsbot
            ./.env.sample
            ./README.md
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - name: Upload debug build artifact
        uses: actions/upload-artifact@v2
        with:
          name: piwarsbot-debug
          path: ./target/debug/piwarsbot

      - name: Cache cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
            ~/.cargo/bin
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
